package com.github.search.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.github.search.bean.Owner;
import com.github.search.bean.Repo;

import com.github.search.greendao.OwnerDao;
import com.github.search.greendao.RepoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ownerDaoConfig;
    private final DaoConfig repoDaoConfig;

    private final OwnerDao ownerDao;
    private final RepoDao repoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ownerDaoConfig = daoConfigMap.get(OwnerDao.class).clone();
        ownerDaoConfig.initIdentityScope(type);

        repoDaoConfig = daoConfigMap.get(RepoDao.class).clone();
        repoDaoConfig.initIdentityScope(type);

        ownerDao = new OwnerDao(ownerDaoConfig, this);
        repoDao = new RepoDao(repoDaoConfig, this);

        registerDao(Owner.class, ownerDao);
        registerDao(Repo.class, repoDao);
    }
    
    public void clear() {
        ownerDaoConfig.clearIdentityScope();
        repoDaoConfig.clearIdentityScope();
    }

    public OwnerDao getOwnerDao() {
        return ownerDao;
    }

    public RepoDao getRepoDao() {
        return repoDao;
    }

}
